YTDLManager/urls.py
from django.contrib import admin
from django.urls import include, path

from downloader.views import index

urlpatterns = [
    path("", include("music_manager.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("downloads", include("downloader.urls")),
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path

from . import views

downloader/urls.py
from django.urls import path

from . import views

app_name = "downloader"
urlpatterns = [
    path("", views.index, name="home"),
    #path("<str:user>/", views.requests, name="requests"),
    #path("<str:user>/<int:item_id>/", views.item, name="item"),
    path("download/", views.download, name="download"),
    path("completed/", views.completed, name="completed")
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
     {% include 'header.html' %}

     <!-- Main content block -->
     {% block content %}
     <!-- Default content can go here (optional) -->
     {% endblock %}

     {% include 'footer.html' %}

     <script src="{% static 'script.js' %}"></script>
</body>
</html>

templates/footer.html
<footer>
    <p>&copy; 2023 My Website. All rights reserved.</p>
</footer>

templates/header.html
<header>
    <h1>{% block header_title %}My Website{% endblock %}</h1>
    <nav>
        <a href="{% url 'downloader:home' %}" class="button">Home</a>

        <button id="theme-toggle" class="button">Toggle Dark Mode</button>
    </nav>
</header>

templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
     {% include 'header.html' with %}

     <!-- Main content block -->
     {% block content %}
     <!-- Default content can go here (optional) -->
     {% endblock %}

     {% include 'footer.html' %}

     <script src="{% static 'script.js' %}"></script>
</body>
</html>